POST http://localhost:9000/api/auth/register
Content-Type: application/json

{
    "username": "Alex",
    "password": "1234"
}

####

POST http://localhost:9000/api/auth/login
Content-Type: application/json

{
    "username": "Alex",
    "password": "1234"
}

####

GET http://localhost:9000/api/jokes
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWJqZWN0IjoyLCJ1c2VybmFtZSI6IkFsZXgiLCJpYXQiOjE3MjU5MTkyMTgsImV4cCI6MTcyNjAwNTYxOH0.PqxN7haOGqEs3k2xw1zxsLBCbqCgHjk-hu05r3eIHC4