POST http://localhost:9000/api/auth/register
Content-Type: application/json

{
    "username": "Jacob",
    "password": "1234"
}

####

POST http://localhost:9000/api/auth/login
Content-Type: application/json

{
    "username": "Alex",
    "password": "1234"
}

####

GET http://localhost:9000/api/jokes
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWJqZWN0IjoyLCJ1c2VybmFtZSI6IkFsZXgiLCJpYXQiOjE3MjU3NDU3MzYsImV4cCI6MTcyNTgzMjEzNn0.5ZgoYNvZyFSiW1jf0JPSvGodguaTbx8VDUUf-fv7GAA